import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'
import Navbar from '@/components/Navbar'
import Provider from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Apollo IoT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, session
}: {
  children: React.ReactNode, session: any
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <Navbar />
          {children}
          <ToastContainer />
        </Provider>
      </body>
    </html>
  )
}
